### ISSUE TITLE
TUROCHAMP for Java?

### ISSUE THREAD

**Issue by SLW2K** [mdoege/nimTUROCHAMP#1]
Just wondering if you might make a Java version that could work in Arena. It's a very fun program!

Shawn

**Comment by mdoege** [comment]
Why Java? Both nimTUROCHAMP and PyTuroChamp (https://github.com/mdoege/PyTuroChamp) work just fine in Arena as they are.

I used to offer PyTuroChamp binaries on Google Drive for easier installation (especially on Windows), but I took them down because they were based an older PTC version. But even without a binary, running a Python program is not too difficult on any operating system. Certainly no harder than downloading and installing Java...

**Comment by SLW2K** [comment]
Because I use Windows and Java 8 is the standard, and the alternative to Windows executables is usually Java such as Pirarucu (https://github.com/ratosh/pirarucu/releases). Anyway I'll figure it out, thanks.

Shawn

**Comment by mdoege** [comment]
I think Java is an unusual language choice for a chess engine. Typically they are written in C or a related language for maximum performance. Turochamp generally does not need a lot of performance however, so even plain Python works fine.

Apart from my Nim and Python versions of Turochamp, there is also this Go version you could try: https://github.com/herohde/morlock

Finally, here is a Windows EXE of Sargon: https://github.com/billforsternz/retro-sargon/releases Sargon is probably a little stronger than Turochamp, although that also depends on the level/search depth.

**Comment by SLW2K** [comment]
Yes, that's what I thought at first. Pirarucu 3.3.5 is *very* strong engine, I think it's 3200+ ELO from a few tests I have done. In fact have the Sargon I engine you mentioned, and it is much stronger than the original but I can beat it (I'm rated over 2000). It needs about 15 seconds a move to get to ply 6-7, and 30 seconds to get to 8-9 ply. It still uses it's original search method, so it is slow. He boosted it to 20 ply max, but I have seen it only get to 10 ply on 60 seconds per move. I have been meaning to play it at 5 minutes per move, but I don't have the patience...ha ha.

Have you played Sunfish, and how strong is it?

Shawn

**Comment by SLW2K** [comment]
Well, I tried to do Python & PyPy and found it would be some work and having to learn a new language and all that comes with it, so I have declined. Anyway, if you would ever consider doing a Java 8 port of this, let me know. At least I can play a few rounds on the browser.

Shawn Weber
