### ISSUE TITLE
Nim and threads ?

### ISSUE THREAD

**Issue by tissatussa** [mdoege/nimTUROCHAMP#4]
By creating this Issue i try to communicate with you, being a Nim programmer, to get my head around some code concerning threads, and so.. It has little to do with NimTUROCHAMP, but i see no other way to contact you - maybe it's better to make this Issue into a "Discussion"?

It's about my recent Issue here :

**how to feed commands to external process and catch output**
https://github.com/Araq/malebolgia/issues/28

As you can see Andreas Rumpf -creator of Nim!- just gave me an answer but unfortunately it's still not clear to me :

_Read https://github.com/Araq/nimedit/blob/master/console.nim#L318 for inspiration.
Having said that, you're better off using a library instead of an external process, interprocess communication is usually a clusterfuck on UNIX._

I'm surprised it takes so many code lines to accomplish what i want : start a process by executing a binary and communicate with it by feeding stdin and catching stdout (the way i understand it).
Btw. i think `stockfish` can be a clear example, being able to communicate with this binary by its `UCI` protocol.

Studying that `nimedit` code i have many questions .. i see many (26!) `proc` definitions, a few `type` and `const` declarations, and between (?) those a few lines which seem to be executed as 'main' - the way i understand Nim.. :

```nim
# --- lines 309 - 314:

# Threading channels
var requests: Channel[string]
requests.open()
var responses: Channel[string]
responses.open()
# Threading channels END

# --- lines 375,376:

var backgroundThread: Thread[void]
createThread[void](backgroundThread, execThreadProc)
```

here, `execThreadProc` is defined at line 318, the one Andreas linked to, but how to make `stockfish` run this way? I need an example..

Btw. opening `requests` and `responses` (lines 310-313) by a using a `Channel` involves thread(s), which -according to https://nim-lang.org/1.6.6/threads.html - should be 'activated' by compiling with the `--threads:on` command line switch, not `import system/threads` (indeed nimedit doesn't import that).

so, how to run `stockfish` by the `createThread` line ?

[ i'm on Xubuntu 22.04, using Nim v1.6.12 ]

**Comment by tissatussa** [comment]
> ..you're better off using a library instead of an external process..

unclear : `stockfish` is an external process, not a library..

isn't `Malebolgia` a library? i'm confused..
does he mean to say "you're better off using a library (like Malebolgia?) to run an external process" ?

**Comment by mdoege** [comment]
I think you should better ask this on the Nim forum. Personally I have not looked into starting external programs such as an engine from Nim, so I can be of little help here…
